name: GateKeeperOps

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  scan-and-deploy:
    name: Secure Scan + Deploy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-southeast-2
      ACCOUNT_ID_PROD: "256457979819"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install tools
        run: |
          pip install aws-sam-cli cfn-lint checkov bandit

      - name: Validate SAM Template
        run: sam validate

      - name: Lint CloudFormation
        run: cfn-lint template.yaml

      - name: Run Checkov
        run: checkov -f template.yaml --skip-check CKV_AWS_115 --skip-check CKV_AWS_117

      - name: Run Bandit (Code Scan on all Lambda folders)
        run: |
          for dir in lambdas/*; do
            if [ -d "$dir" ]; then
              echo "Scanning $dir with Bandit..."
              bandit -r "$dir" -lll || true
            fi
          done

      - name: SAM Build
        run: sam build

      - name: AI Infra Review
        run: echo "Placeholder for Bedrock integration"

      - name: Set Deployment Role by Branch
        id: set-role
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "role_to_assume=arn:aws:iam::${ACCOUNT_ID_PROD}:role/GitHubActionsSAMDeployRole" >> $GITHUB_ENV
          else
            echo "role_to_assume=arn:aws:iam::000000000000:role/OtherRole" >> $GITHUB_ENV
          fi

      - name: Debug IAM Role
        run: |
          echo "IAM Role: ${{ env.role_to_assume }}"

      - name: Retrieve GitHub OIDC Token
        id: oidc-token
        uses: actions/github-script@v6
        with:
          script: |
            const token = await core.getIDToken();
            core.setOutput("token", token);

      - name: Decode OIDC Token Payload
        run: |
          echo "${{ steps.oidc-token.outputs.token }}" > token.jwt
          cut -d '.' -f2 token.jwt | base64 --decode | jq .

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.role_to_assume }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: SAM Deploy
        run: |
          sam deploy \
            --stack-name gatekeeperops-dev \
            --capabilities CAPABILITY_IAM \
            --region ap-southeast-2 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
